// libs/react-component/src/components/WeatherConsumer.jsx
// react component
import { useRef, useMemo } from "react";
import styled from "styled-components";
import { Tag, Icon } from "tiny-ui";
import "tiny-ui/dist/styles/index.css";

const ComponentContainer = styled.div`
  border: 1px dashed #f23288;
  border-radius: 10px;
  width: 300px;
  box-sizing: border-box;
  padding: 20px;
`;

export default function WeatherConsumer(props) {
  // @ts-ignore
  window.globalVar1 = "reactGlobalVar1";
  // @ts-ignore
  window.__RAW_WINDOW__?.console.log("react fc", window.globalVar1);

  const { city, temperature, onMsg } = props;

  const compRef = useRef(null);

  const centigrade = useMemo(() => `${temperature || "--"}℃`, [temperature]);

  const onCompClick = () => {
    if (typeof onMsg === "function") onMsg(city);
  };

  return (
    <ComponentContainer
      ref={compRef}
      className="react-consumer"
      onClick={onCompClick}
    >
      <h1 part="title" style={{ color: "#ddd" }}>
        &lt;react-weather-consumer/&gt;
      </h1>
      <Icon name="skin" size={30} />
      {city}: <Tag color="volcano">{centigrade}</Tag>
    </ComponentContainer>
  );
}

// libs/vue2-component/src/components/WeatherConsumer.vue
<script>
// vue 2 component
import { defineComponent, h, computed, isVue2 } from "vue-demi";

export default defineComponent({
  props: {
    city: {
      type: String,
      default: "unknown",
    },
    temperature: Number,
  },
  setup(props, { emit }) {
    const vueVer = isVue2 ? 2 : 3;

    window.globalVar1 = "vue2GlobalVar1";
    window.__RAW_WINDOW__?.console.log("setup2", vueVer, window.globalVar1);
    console.log(window, window.__COMPONENT_HOST_VUE_VERSION__);

    const centigrade = computed(() => `${props.temperature || "--"}℃`);
    const onClick = () => {
      console.log("onClick", props.city);
      emit("msg", props.city);
    };

    return () =>
      h(
        "div",
        {
          class: "consumer",
          ...(isVue2
            ? {
                on: {
                  click: onClick,
                },
              }
            : {
                onClick: onClick,
              }),
        },
        [
          h("h1", {
            style: "color: #336699",
            domProps: {
              innerHTML: "&lt;vue2-weather-consumer/&gt;",
            },
          }),
          `${props.city}: ${centigrade.value}`,
          h("hr"),
          `i am running in Vue${vueVer}`,
        ]
      );
  },
});
</script>

<style scoped>
.consumer {
  border: 1px solid var(--vue2-color, #000);
  border-radius: 10px;
  width: 300px;
  box-sizing: border-box;
  padding: 20px;
}
</style>
